# Generated by Django 5.0.1 on 2025-03-04 06:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('parameter', '0007_speciality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titre')),
                ('number_of_hours', models.FloatField(max_length=10, verbose_name="Nombre d'heures de prestation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_grade_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=25, unique=True, verbose_name='Matricule')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Matricule')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nom')),
                ('type', models.CharField(blank=True, choices=[('permanent', 'Permenant'), ('visiteur', 'visiteuu')], default='permanant', max_length=25, null=True, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_grade_set', to='teacher.grade', verbose_name='Grade')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_orientation_set_set', to='parameter.filiere', verbose_name='Orientation')),
                ('specialities', models.ManyToManyField(related_name='teacher_specialities_set', to='parameter.speciality', verbose_name='Specialités')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'teachers',
            },
            bases=('authentication.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
