# Generated by Django 5.0.1 on 2025-03-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0007_speciality'),
        ('teacher', '0002_alter_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_orientation_set_set', to='parameter.filiere', verbose_name='Orientation'),
        ),
    ]
