# Generated by Django 5.0.1 on 2025-03-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0007_speciality'),
        ('teacher', '0003_alter_teacher_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='specialities',
        ),
        migrations.CreateModel(
            name='TeacherSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciality_teacher_set', to='parameter.speciality', verbose_name='Specialité')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_speciality_set', to='teacher.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Enseignant et specialité',
                'verbose_name_plural': 'Enseignants et specialiés',
                'db_table': 'teachers_specialities',
            },
        ),
    ]
