# Generated by Django 5.0.1 on 2025-03-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0008_section_filiere_section'),
        ('teacher', '0004_remove_teacher_specialities_teacherspeciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='orientation',
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_orientation_set_set', to='parameter.section', verbose_name='Orientation'),
        ),
    ]
