# Generated by Django 5.0.1 on 2025-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_orientation_teacher_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
    ]
