# Generated by Django 5.0.1 on 2025-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_grade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='number_of_hours',
            field=models.FloatField(default=0, max_length=10, verbose_name="Nombre d'heures de prestation"),
        ),
    ]
