# Generated by Django 5.0.1 on 2025-03-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0009_alter_filiere_section'),
        ('student', '0004_alter_student_phone'),
        ('teachers', '0002_alter_teacher_name_alter_teacher_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProjet',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='-', max_length=250, verbose_name='Nom du groupe')),
                ('subject', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sujet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectation_academic_year_set', to='parameter.academicyear', verbose_name='Année academique')),
                ('affected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectation_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('students', models.ManyToManyField(related_name='affectations_students_set', to='student.student', verbose_name='Etudiants')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_teacher_set', to='teachers.teacher', verbose_name='Enseignants')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_type_project_set', to='affectation.typeprojet', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'db_table': 'affectations',
            },
        ),
    ]
