# Generated by Django 5.0.1 on 2025-04-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0002_remove_affectation_students_affectation_student'),
        ('parameter', '0009_alter_filiere_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='type',
        ),
        migrations.AddField(
            model_name='affectation',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectation_promotion_set', to='parameter.promotion', verbose_name='Promotion'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectation_section_set', to='parameter.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='student',
            field=models.CharField(default='-', max_length=100, verbose_name='Nom du groupe'),
        ),
    ]
