# Generated by Django 5.0.1 on 2025-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0003_remove_affectation_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='matricule',
            field=models.CharField(default='-', max_length=100, verbose_name='Matricule'),
        ),
    ]
