# Generated by Django 5.0.1 on 2025-05-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0004_affectation_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='date_deposit_fees',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date payement frais de depot'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_management_fees',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date payement frais de direction'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_teacher_amount_collected',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date perception de l'enseignant"),
        ),
        migrations.AddField(
            model_name='affectation',
            name='deposit_fees',
            field=models.FloatField(default=0.0, verbose_name='Frais de depot'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='management_fees',
            field=models.FloatField(default=0.0, verbose_name='Frais de direction'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='teacher_amount_collected',
            field=models.FloatField(default=0.0, verbose_name="Montant percu par l'enseignant"),
        ),
    ]
