# Generated by Django 5.0.1 on 2025-05-02 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0005_affectation_date_deposit_fees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='student',
            field=models.CharField(default='-', max_length=100, verbose_name="Nom de l'etudiant"),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='teacher_amount_collected',
            field=models.FloatField(default=0.0, verbose_name="Percu par l'enseignant"),
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_fees', models.FloatField(default=0.0, verbose_name='Frais de direction')),
                ('deposit_fees', models.FloatField(default=0.0, verbose_name='Frais de depot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prevision_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Prevision',
                'verbose_name_plural': 'Previsions',
                'db_table': 'previsions',
            },
        ),
    ]
