# Generated by Django 5.0.1 on 2025-05-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0006_alter_affectation_student_and_more'),
        ('parameter', '0009_alter_filiere_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prevision_academic_year_set', to='parameter.academicyear', verbose_name='Année academique'),
            preserve_default=False,
        ),
    ]
