# Generated by Django 5.0.1 on 2025-05-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0007_prevision_academic_year'),
        ('parameter', '0009_alter_filiere_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prevision_promotion_set', to='parameter.promotion', verbose_name='Promotion'),
            preserve_default=False,
        ),
    ]
