# Generated by Django 5.0.1 on 2025-10-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0008_prevision_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='date_teacher_deposit_amount_collected',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date perception de l'enseignant"),
        ),
        migrations.AddField(
            model_name='affectation',
            name='teacher_deposit_amount_collected',
            field=models.FloatField(default=0.0, verbose_name="Percu par l'enseignant"),
        ),
    ]
