# Generated by Django 5.0.1 on 2025-03-17 14:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('parameter', '0009_alter_filiere_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='grade')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('number_of_hours', models.FloatField(default=0, max_length=10, verbose_name="Nombre d'heures de prestation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_grade_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'gradess',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=25, unique=True, verbose_name='Matricule')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Matricule')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nom')),
                ('type', models.CharField(blank=True, choices=[('permanent', 'Permenant'), ('visiteur', 'visiteuu')], default='permanant', max_length=25, null=True, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_grades_set', to='teachers.grade', verbose_name='Grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_sections_set', to='parameter.section', verbose_name='Orientation')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'tb_teachers',
            },
            bases=('authentication.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
