# Generated by Django 5.0.1 on 2025-04-28 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0009_alter_filiere_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finaliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=25, unique=True, verbose_name='Matricule')),
                ('names', models.CharField(max_length=100, verbose_name='Noms')),
                ('date_and_place_of_birth', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('gender', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=10, verbose_name='Sexe')),
                ('nationality', models.CharField(default='Congolaise', max_length=256, verbose_name='Nationalité')),
                ('previous_training', models.CharField(blank=True, max_length=100, null=True, verbose_name='FORMATION ANTERIEURE')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statut')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='TELEPHONE')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalist_acadmic_year_set', to='parameter.academicyear', verbose_name='Année academique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalist_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalist_orientation_set', to='parameter.filiere', verbose_name='Orientation')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalist_promotion_set', to='parameter.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Finaliste',
                'verbose_name_plural': 'Finalistes',
                'db_table': 'finaliste',
            },
        ),
    ]
