# Generated by Django 5.0.1 on 2025-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaliste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationLiaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
