# Generated by Django 5.0.1 on 2025-03-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0009_alter_filiere_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classeur',
                'verbose_name_plural': 'Classeurs',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=250, verbose_name='Ref')),
                ('object', models.CharField(default='-', max_length=250, verbose_name='Objet')),
                ('sender_or_reciver', models.CharField(blank=True, max_length=200, null=True, verbose_name='Expeditaire/ Destinataire')),
                ('_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_package_set', to='parameter.academicyear', verbose_name='Année academique')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folder_file_set', to='archive.folder', verbose_name='Classeur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
    ]
