# Generated by Django 5.0.1 on 2025-03-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('parameter', '0009_alter_filiere_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='-', max_length=250, verbose_name='REF')),
                ('object', models.CharField(default='-', max_length=250, verbose_name='OBJET/ RESUME')),
                ('sender_or_reciver', models.CharField(blank=True, max_length=200, null=True, verbose_name='EXPEDITAIRE/ DESTINATAIRE')),
                ('num_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='NUMERO DE LA LETTRE')),
                ('_date', models.DateField(verbose_name='DATE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_package_set', to='parameter.academicyear', verbose_name='ANNE ACADEMIQUE')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folder_file_set', to='archive.folder', verbose_name='CLASSEUR')),
            ],
            options={
                'verbose_name': 'Lettre',
                'verbose_name_plural': 'Lettres',
                'db_table': 'leters',
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
