# Generated by Django 5.0.1 on 2025-02-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=25, unique=True, verbose_name='Matricule')),
                ('names', models.CharField(max_length=100, verbose_name='Noms')),
                ('date_of_birth', models.CharField(max_length=25, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=25, verbose_name='Lieu de naissance')),
                ('gender', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=10, verbose_name='Sexe')),
                ('nationality', models.CharField(default='Congolaise', max_length=256, verbose_name='Nationalité')),
                ('previous_training', models.CharField(blank=True, max_length=100, null=True, verbose_name='FORMATION ANTERIEURE')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statut')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='TELEPHONE')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to='students/defaut_document/', verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_acadmic_year_set', to='parameter.academicyear', verbose_name='Année academique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studendt_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('documents', models.ManyToManyField(related_name='student_documents_set', to='parameter.documentfolde', verbose_name='Elements du dossier')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_orientation_set', to='parameter.filiere', verbose_name='Orientation')),
            ],
            options={
                'verbose_name': 'Etudiants',
                'verbose_name_plural': 'Etudiant',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='AttachementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to='students/attachement/', verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachement_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_file_attachement_set', to='student.student', verbose_name='Etudiant')),
            ],
            options={
                'verbose_name': 'Attachemnts',
                'verbose_name_plural': 'Attachement',
                'db_table': 'attachements',
            },
        ),
    ]
