# Generated by Django 5.0.1 on 2025-02-19 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachementfile',
            options={'verbose_name': 'Attachement', 'verbose_name_plural': 'Attachements'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='date_and_place_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Lieu de naissance'),
            preserve_default=False,
        ),
    ]
