# Generated by Django 5.0.1 on 2025-02-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_promotion'),
        ('student', '0002_alter_attachementfile_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_promotion_set', to='parameter.promotion', verbose_name='Promotion'),
        ),
    ]
