# Generated by Django 5.0.1 on 2025-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='TELEPHONE'),
        ),
    ]
