# Generated by Django 5.0.1 on 2025-02-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Année Academique', 'verbose_name_plural': 'Années Academique'},
        ),
        migrations.AlterModelOptions(
            name='documentfolde',
            options={'verbose_name': 'Element du dossier', 'verbose_name_plural': 'Elements du dossier'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'Orientation', 'verbose_name_plural': 'Orientations'},
        ),
    ]
