# Generated by Django 5.0.1 on 2025-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0004_filiere_sigle'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='-', max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
    ]
