# Generated by Django 5.0.1 on 2025-03-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0007_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=50, unique=True, verbose_name='Sigle')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parameter.section', verbose_name='Section'),
        ),
    ]
